stages:
    - deps-prepare
    - deps
    - build
    - release

variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    
tdlib-prepare:
    stage: deps-prepare
    image: clickable/ci-16.04-amd64
    script:
        - clickable build-libs tdlib-prepare --arch amd64
    cache:
        key: deps-cache
        paths:
            - libs/vendor/tdlib

tdlib:
    stage: deps
    image: clickable/ci-16.04-armhf
    script:
        - clickable build-libs tdlib --arch armhf
    cache:
        key: deps-cache
        paths:
            - build/tdlib/arm-linux-gnueabihf
            - libs/vendor/tdlib

tg-plus:
    stage: build
    image: clickable/ci-16.04-armhf
    script:
        - clickable clean build click-build
    cache:
        key: deps-cache
        paths:
            - build/tdlib/arm-linux-gnueabihf
            - libs/vendor/tdlib
            - libs/quickflux
    artifacts:
        paths:
            - build/teleports/*.click
        expire_in: 1 week
        
release:
    stage: release
    script:
        - release.sh
    only:
        - release-dev
        - release
        
