stages:
    - deps-prepare
    - deps
    - build
    - release

variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    
tdlib-prepare:
    stage: deps-prepare
    image: clickable/ci-16.04-amd64
    script:
        - clickable build-libs tdlib-prepare --arch amd64
    cache:
        key: deps-cache
        paths:
            - libs/vendor/tdlib

tdlib:
    stage: deps
    image: clickable/ci-16.04-armhf
    script:
        - clickable build-libs tdlib --arch armhf
    cache:
        key: deps-cache
        paths:
            - build/tdlib/arm-linux-gnueabihf
            - libs/vendor/tdlib

tg-plus:
    stage: build
    image: clickable/ci-16.04-armhf
    script:
        - clickable clean build click-build
    cache:
        key: deps-cache
        paths:
            - build/tdlib/arm-linux-gnueabihf
            - libs/vendor/tdlib
            - libs/quickflux
    artifacts:
        paths:
            - build/teleports/*.click
        expire_in: 1 week
        
release-dev:
    stage: release
    script: >
        - '[ -z "$CI_COMMIT_TAG" ] && exit 1'
        - curl -H "JOB_TOKEN: $CI_JOB_TOKEN" --data '{ "name": "Development Release $CI_COMMIT_TAG", "tag_name": "$CI_COMMIT_TAG", "description": "Recurring TELEports developer release, only for testing!" }' --request POST http://gitlab.com/api/v4/projects/8146239/releases
    only:
        - release-dev
        
release-prod:
    stage: release
    script:
        - '[ -z "$CI_COMMIT_TAG" ] && exit 1'
        - curl -H "JOB_TOKEN: $CI_JOB_TOKEN" --data '{ "name": "Release $CI_COMMIT_TAG", "tag_name": "$CI_COMMIT_TAG", "description": "This is the current stable release of TELEports" }' --request POST http://gitlab.com/api/v4/projects/8146239/releases
    only:
        - release

