stages:
    - deps-prepare
    - deps
    - build
    - publish
    - debug

variables:
    GIT_SUBMODULE_STRATEGY: 'recursive'
    DOCKER_DRIVER: overlay2
    CLICKABLE_VERSION: "6.21.0"

cache: &tdlib_cache
    key: '$CI_JOB_NAME-$CI_COMMIT_REF_SLUG-1.7.9'
    untracked: true

.debug: &debug
    stage: debug
    variables:
        CLICKABLE_DEBUG_BUILD: "1"
        CLICKABLE_ENV_TDLIB_DEBUG: "1"
    when: manual

.armhf: &armhf
    variables:
        ARCH: "armhf"
        ARCH_TRIPLET: "arm-linux-gnueabihf"

.arm64: &arm64
    variables:
        ARCH: "arm64"
        ARCH_TRIPLET: "aarch64-linux-gnu"

.amd64: &amd64
    variables:
        ARCH: "amd64"
        ARCH_TRIPLET: "x86_64-linux-gnu"


.tdlib:
    image: "clickable/ci-16.04-$ARCH:$CLICKABLE_VERSION"
    stage: deps
    dependencies:
        - tdlib-prepare
    script: 'clickable build-libs tdlib --arch $ARCH'
    cache:
        <<: *tdlib_cache
        paths:
            - "build/$ARCH_TRIPLET/tdlib"
    artifacts:
        paths:
            - "build/$ARCH_TRIPLET/tdlib/install"
        expire_in: 1 week

.rlottie:
    image: "clickable/ci-16.04-$ARCH:$CLICKABLE_VERSION"
    stage: deps-prepare
    script: 'clickable build-libs rlottie --arch $ARCH'
    artifacts:
        paths:
            - "build/$ARCH_TRIPLET/rlottie/install"
        expire_in: 1 week

.rlottie-qml:
    image: "clickable/ci-16.04-$ARCH:$CLICKABLE_VERSION"
    stage: deps
    script: 'clickable build-libs rlottie-qml --arch $ARCH'
    artifacts:
        paths:
            - "build/$ARCH_TRIPLET/rlottie-qml/install"
        expire_in: 1 week

.quickflux:
    image: "clickable/ci-16.04-$ARCH:$CLICKABLE_VERSION"
    stage: deps
    script: 'clickable build-libs quickflux --arch $ARCH'
    artifacts:
        paths:
            - "build/$ARCH_TRIPLET/quickflux/install"
        expire_in: 1 week

.teleports:
    image: "clickable/ci-16.04-$ARCH:$CLICKABLE_VERSION"
    stage: build
    script: 'clickable clean-build --arch $ARCH'
    artifacts:
        paths:
            - "build/$ARCH_TRIPLET/app"
        expire_in: 1 week


tdlib-prepare:
    stage: deps-prepare
    image: "clickable/ci-16.04-amd64:$CLICKABLE_VERSION"
    script: 'clickable build-libs tdlib-prepare --arch amd64'
    cache:
        <<: *tdlib_cache
        paths:
            - "build/x86_64-linux-gnu/tdlib-prepare"
            - "libs/vendor/tdlib"
    artifacts:
        paths:
            - "libs/vendor/tdlib"
        expire_in: 1 week


tdlib-armhf:
    <<: *armhf
    extends: .tdlib

tdlib-arm64:
    <<: *arm64
    extends: .tdlib

tdlib-amd64:
    <<: *amd64
    extends: .tdlib

rlottie-armhf:
    <<: *armhf
    extends: .rlottie

rlottie-arm64:
    <<: *arm64
    extends: .rlottie

rlottie-amd64:
    <<: *amd64
    extends: .rlottie

rlottie-qml-armhf:
    <<: *armhf
    extends: .rlottie-qml
    dependencies:
        - rlottie-armhf

rlottie-qml-arm64:
    <<: *arm64
    extends: .rlottie-qml
    dependencies:
        - rlottie-arm64

rlottie-qml-amd64:
    <<: *amd64
    extends: .rlottie-qml
    dependencies:
        - rlottie-amd64

quickflux-armhf:
    <<: *armhf
    extends: .quickflux

quickflux-arm64:
    <<: *arm64
    extends: .quickflux

quickflux-amd64:
    <<: *amd64
    extends: .quickflux

teleports-armhf:
    <<: *armhf
    dependencies:
        - tdlib-armhf
        - quickflux-armhf
        - rlottie-armhf
        - rlottie-qml-armhf
    extends: .teleports

teleports-arm64:
    <<: *arm64
    dependencies:
        - tdlib-arm64
        - quickflux-arm64
        - rlottie-arm64
        - rlottie-qml-arm64
    extends: .teleports

teleports-amd64:
    <<: *amd64
    dependencies:
        - tdlib-amd64
        - quickflux-amd64
        - rlottie-amd64
        - rlottie-qml-amd64
    extends: .teleports


teleports-armhf-debug:
    <<: *debug
    extends: teleports-armhf

teleports-arm64-debug:
    <<: *debug
    extends: teleports-arm64

teleports-amd64-debug:
    <<: *debug
    extends: teleports-amd64


publish:
    stage: publish
    image: "clickable/ci-16.04-armhf:$CLICKABLE_VERSION"
    rules:
        - if: $CI_COMMIT_TAG
    script:
        - 'clickable publish "$CI_COMMIT_MESSAGE"'
        - 'clickable publish --arch arm64'
        - 'clickable publish --arch amd64'
    dependencies:
        - teleports-armhf
        - teleports-arm64
        - teleports-amd64
    artifacts:
        paths:
            - build/arm-linux-gnueabihf/app/*.click
            - build/aarch64-linux-gnu/app/*.click
            - build/x86_64-linux-gnu/app/*.click
        expire_in: 30 days
