stages:
    - deps-prepare
    - deps
    - build
    - release

variables:
    GIT_SUBMODULE_STRATEGY: "recursive"
    
tdlib-prepare:
    stage: deps-prepare
    image: clickable/ci-16.04-amd64
    script:
        - clickable build-libs tdlib-prepare --arch amd64
    cache:
        key: deps-cache
        paths:
            - build/tdlib
            - build/tdlib-prepare
            - libs/vendor/tdlib

tdlib:
    stage: deps
    image: clickable/ci-16.04-armhf
    script:
        - clickable build-libs tdlib --arch armhf
    cache:
        key: deps-cache
        paths:
            - build/tdlib
            - build/tdlib-prepare
            - libs/vendor/tdlib

teleports:
    stage: build
    image: clickable/ci-16.04-armhf
    script:
        - clickable build click-build
    cache:
        key: deps-cache
        policy: pull
        paths:
            - build/tdlib
            - build/tdlib-prepare
            - libs/vendor/tdlib
    artifacts:
        paths:
            - build/teleports/*.click
        expire_in: 1 week
        
release:
    stage: release
    script:
        - /builds/Flohack74/teleports/release.sh
    only:
        - ^(release-)(\d+\.)?(\d+\.)?(\*|\d+)$
    except:
        - branches
        
